services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libzbar0
      pip install -r requirements.txt
    startCommand: uvicorn bot:app --host 0.0.0.0 --port $PORT
